# Generated by Django 4.1 on 2022-08-09 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_company_name_alter_customuser_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='company',
            new_name='user_company',
        ),
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Company owner'),
        ),
    ]
